//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/GlobalInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GlobalInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GlobalInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GlobalInputActions"",
    ""maps"": [
        {
            ""name"": ""StartNewPlayer"",
            ""id"": ""bebcbcf7-6a79-49a6-ae3b-0ab6079876b4"",
            ""actions"": [
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""fdfe0761-a278-4ef3-94af-14361fa19efd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""428ce58a-1345-42f7-8cd8-e22b42de2746"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1def2a6d-503d-4316-af7a-764356a8ff9b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // StartNewPlayer
        m_StartNewPlayer = asset.FindActionMap("StartNewPlayer", throwIfNotFound: true);
        m_StartNewPlayer_Start = m_StartNewPlayer.FindAction("Start", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // StartNewPlayer
    private readonly InputActionMap m_StartNewPlayer;
    private List<IStartNewPlayerActions> m_StartNewPlayerActionsCallbackInterfaces = new List<IStartNewPlayerActions>();
    private readonly InputAction m_StartNewPlayer_Start;
    public struct StartNewPlayerActions
    {
        private @GlobalInputActions m_Wrapper;
        public StartNewPlayerActions(@GlobalInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Start => m_Wrapper.m_StartNewPlayer_Start;
        public InputActionMap Get() { return m_Wrapper.m_StartNewPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StartNewPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IStartNewPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_StartNewPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StartNewPlayerActionsCallbackInterfaces.Add(instance);
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
        }

        private void UnregisterCallbacks(IStartNewPlayerActions instance)
        {
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
        }

        public void RemoveCallbacks(IStartNewPlayerActions instance)
        {
            if (m_Wrapper.m_StartNewPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStartNewPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_StartNewPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StartNewPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StartNewPlayerActions @StartNewPlayer => new StartNewPlayerActions(this);
    public interface IStartNewPlayerActions
    {
        void OnStart(InputAction.CallbackContext context);
    }
}
